name: Delete PR staging branch

on:
  pull_request_target:
    branches: ["*/advisory-improvement-*"]
    types: [closed]
    paths:
      - "advisories/**"
  workflow_dispatch:

jobs:
  delete-staging-branch:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: delete staging branch
       env:
         STAGING_BRANCH: ${{ github.event.pull_request.base.ref }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         set -xeo pipefail
         git push origin --delete $STAGING_BRANCH
